version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_ADMIN: admin
    env_file:
      - .env
    ports:
      - "8080:8080"
    command:
      - "start-dev"
      - "--proxy"
      - "edge"
      - "--hostname-strict"
      - "false"
  keycloak-config-cli:
    image: quay.io/adorsys/keycloak-config-cli:5.6.1-21.0.1
    env_file:
      - .env
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      KEYCLOAK_URL: "http://keycloak:8080/"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      IMPORT_FILES: "/config/*"
      IMPORT_VARSUBSTITUTION_ENABLED: "true"
    volumes:
      - "./config/:/config/"
  demo-frontend:
    build:
      context: ./demo-frontend/
      args:
        KEYCLOAK_URL: "$KEYCLOAK_URL"
    ports:
      - "3000:8080"

